In [2]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline

In [3]:
df = pd.read_csv('yds_train2018.csv')
df.head()

S_No  Year  Month  Week Merchant_ID  Product_ID    Country     Sales
0     1  2013      1     1     ar00001           1  Argentina  157500.0
1     2  2013      1     1     ar00003           1  Argentina   39375.0
2     3  2013      1     1     ar00004           1  Argentina   15750.0
3     4  2013      1     1     ar00007           1  Argentina   47250.0
4     5  2013      1     1     ar00008           1  Argentina  283500.0

In [4]:
df

S_No  Year  Month  Week Merchant_ID  Product_ID    Country       Sales
0          1  2013      1     1     ar00001           1  Argentina   157500.00
1          2  2013      1     1     ar00003           1  Argentina    39375.00
2          3  2013      1     1     ar00004           1  Argentina    15750.00
3          4  2013      1     1     ar00007           1  Argentina    47250.00
4          5  2013      1     1     ar00008           1  Argentina   283500.00
5          6  2013      1     1    ar000011           1  Argentina        0.00
6          7  2013      1     1    ar000021           1  Argentina     1575.00
7          8  2013      1     1    ar000023           1  Argentina    47250.00
8          9  2013      1     1    ar000027           1  Argentina        0.00
9         10  2013      1     1    ar000038           1  Argentina        0.00
10        11  2013      1     1    ar000052           1  Argentina   277200.00
11        12  2013      1     1    ar000058           1  Argentina    12600.00
12        13  2013      1     1    ar000059           1  Argentina   126000.00
13        14  2013      1     1    ar000064           1  Argentina  1417500.00
14        15  2013      1     1    ar000065           1  Argentina   472500.00
15        16  2013      1     1    ar000067           1  Argentina    78750.00
16        17  2013      1     1    ar000068           1  Argentina   132300.00
17        18  2013      1     1    ar000070           1  Argentina        0.00
18        19  2013      1     1    ar000074           1  Argentina    94500.00
19        20  2013      1     1    ar000078           1  Argentina     7875.00
20        21  2013      1     1    ar000081           1  Argentina   173250.00
21        22  2013      1     1    ar000083           1  Argentina    22050.00
22        23  2013      1     1    ar000089           1  Argentina   236250.00
23        24  2013      1     1    ar000091           1  Argentina   510300.00
24        25  2013      1     1    ar000095           1  Argentina     9450.00
25        26  2013      1     1    ar000096           1  Argentina     9450.00
26        27  2013      1     1    ar000098           1  Argentina   157500.00
27        28  2013      1     1   ar0000103           1  Argentina     6300.00
28        29  2013      1     2     ar00001           1  Argentina   157500.00
29        30  2013      1     2     ar00002           1  Argentina   315000.00
...      ...   ...    ...   ...         ...         ...        ...         ...
79042  79043  2015     10    44     f000028           4    Finland    18153.97
79043  79044  2015     10    44     f000029           4    Finland       75.58
79044  79045  2015     10    44     f000030           4    Finland    31138.40
79045  79046  2015     10    44     f000031           4    Finland   174813.69
79046  79047  2015     10    44     f000032           4    Finland   193481.60
79047  79048  2015     10    44     f000033           4    Finland   206178.20
79048  79049  2015     10    44     f000034           4    Finland   311082.60
79049  79050  2015     10    44     f000035           4    Finland    13226.27
79050  79051  2015     10    44     f000037           4    Finland    63637.30
79051  79052  2015     10    44     f000039           4    Finland    83439.00
79052  79053  2015     10    44     f000040           4    Finland    64120.86
79053  79054  2015     10    44     f000041           4    Finland   938386.00
79054  79055  2015     10    44     f000042           4    Finland   133925.20
79055  79056  2015     10    44     f000043           4    Finland   283420.50
79056  79057  2015     10    44     f000044           4    Finland    43835.60
79057  79058  2015     10    44     f000045           4    Finland    69532.60
79058  79059  2015     10    44     f000046           4    Finland    93263.90
79059  79060  2015     10    44     f000047           4    Finland    43079.70
79060  79061  2015     10    44     f000048           4   

In [11]:
mylist = []

In [12]:
mylist2 = []

In [30]:
##DATA CLEANING
## This was done in a loop to get total monthly sales(considering weeks and merchants both..summing them up)
for jx in range(2015,2017):
    for ix in range(1,13):
        a = df.loc[(df['Year']==jx) & (df['Month']==ix) & (df['Country']=='Columbia') & (df['Product_ID']==3)]
        #print(a)
        y = a.iloc[0]['S_No']
        x = a['Sales'].sum(axis=0)
        a.loc[y-1,'Sales']=x
        a.drop(['S_No','Merchant_ID','Week'],axis=1,inplace=True)
        mylist2.append(np.asarray(a.loc[y-1]))
np.asarray(mylist2)

c:\users\shashank\miniconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
c:\users\shashank\miniconda3\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


array([[2013, 1, 1, 'Argentina', 34346025.0],
       [2013, 2, 1, 'Argentina', 32005575.0],
       [2013, 3, 1, 'Argentina', 32530050.0],
       ...,
       [2016, 10, 3, 'Columbia', 3196697.4000000004],
       [2016, 11, 3, 'Columbia', 4263236.550000001],
       [2016, 12, 3, 'Columbia', 4351764.899999999]], dtype=object)

In [39]:

mylist2

[array([2013, 1, 1, 'Argentina', 34346025.0], dtype=object),
 array([2013, 2, 1, 'Argentina', 32005575.0], dtype=object),
 array([2013, 3, 1, 'Argentina', 32530050.0], dtype=object),
 array([2013, 4, 1, 'Argentina', 35588700.0], dtype=object),
 array([2013, 5, 1, 'Argentina', 38789100.0], dtype=object),
 array([2013, 6, 1, 'Argentina', 36196650.0], dtype=object),
 array([2013, 7, 1, 'Argentina', 37133775.0], dtype=object),
 array([2013, 8, 1, 'Argentina', 35311500.0], dtype=object),
 array([2013, 9, 1, 'Argentina', 38437875.0], dtype=object),
 array([2013, 10, 1, 'Argentina', 44397675.0], dtype=object),
 array([2013, 11, 1, 'Argentina', 45525375.0], dtype=object),
 array([2013, 12, 1, 'Argentina', 33610500.0], dtype=object),
 array([2014, 1, 1, 'Argentina', 44600850.0], dtype=object),
 array([2014, 2, 1, 'Argentina', 41562675.0], dtype=object),
 array([2014, 3, 1, 'Argentina', 36957375.0], dtype=object),
 array([2014, 4, 1, 'Argentina', 43447950.0], dtype=object),
 array([2014, 5, 1, '

In [40]:
import pickle

with open('outfile', 'wb') as fp:
    pickle.dump(mylist2, fp)

In [20]:
# mylist2