In [54]:
import pickle
with open ('outfile', 'rb') as fp:
    mylist2 = pickle.load(fp)

In [55]:
mylist2

[array([2013, 1, 1, 'Argentina', 34346025.0], dtype=object),
 array([2013, 2, 1, 'Argentina', 32005575.0], dtype=object),
 array([2013, 3, 1, 'Argentina', 32530050.0], dtype=object),
 array([2013, 4, 1, 'Argentina', 35588700.0], dtype=object),
 array([2013, 5, 1, 'Argentina', 38789100.0], dtype=object),
 array([2013, 6, 1, 'Argentina', 36196650.0], dtype=object),
 array([2013, 7, 1, 'Argentina', 37133775.0], dtype=object),
 array([2013, 8, 1, 'Argentina', 35311500.0], dtype=object),
 array([2013, 9, 1, 'Argentina', 38437875.0], dtype=object),
 array([2013, 10, 1, 'Argentina', 44397675.0], dtype=object),
 array([2013, 11, 1, 'Argentina', 45525375.0], dtype=object),
 array([2013, 12, 1, 'Argentina', 33610500.0], dtype=object),
 array([2014, 1, 1, 'Argentina', 44600850.0], dtype=object),
 array([2014, 2, 1, 'Argentina', 41562675.0], dtype=object),
 array([2014, 3, 1, 'Argentina', 36957375.0], dtype=object),
 array([2014, 4, 1, 'Argentina', 43447950.0], dtype=object),
 array([2014, 5, 1, '

In [59]:
mylist3 = np.asarray(mylist2)
mylist_df = pd.DataFrame(mylist3,columns=['Year','Month','Product_Type','Country','Sales'])
mylist_df

Year Month Product_Type    Country        Sales
0    2013     1            1  Argentina   3.4346e+07
1    2013     2            1  Argentina  3.20056e+07
2    2013     3            1  Argentina  3.25300e+07
3    2013     4            1  Argentina  3.55887e+07
4    2013     5            1  Argentina  3.87891e+07
5    2013     6            1  Argentina  3.61966e+07
6    2013     7            1  Argentina  3.71338e+07
7    2013     8            1  Argentina  3.53115e+07
8    2013     9            1  Argentina  3.84379e+07
9    2013    10            1  Argentina  4.43977e+07
10   2013    11            1  Argentina  4.55254e+07
11   2013    12            1  Argentina  3.36105e+07
12   2014     1            1  Argentina  4.46008e+07
13   2014     2            1  Argentina  4.15627e+07
14   2014     3            1  Argentina  3.69574e+07
15   2014     4            1  Argentina   4.3448e+07
16   2014     5            1  Argentina  4.08634e+07
17   2014     6            1  Argentina  4.03767e+07
18   2014     7            1  Argentina   4.3459e+07
19   2014     8            1  Argentina  4.13028e+07
20   2014     9            1  Argentina  4.37834e+07
21   2014    10            1  Argentina  4.37771e+07
22   2014    11            1  Argentina  4.23754e+07
23   2014    12            1  Argentina  4.42433e+07
24   2015     1            1  Argentina  4.65806e+07
25   2015     2            1  Argentina  3.30687e+07
26   2015     3            1  Argentina  3.78646e+07
27   2015     4            1  Argentina  3.51367e+07
28   2015     5            1  Argentina  3.55651e+07
29   2015     6            1  Argentina  4.17564e+07
..    ...   ...          ...        ...          ...
351  2013     5            4    Finland  3.29423e+07
352  2013     6            4    Finland  1.91559e+07
353  2013     7            4    Finland  2.71801e+07
354  2013     8            4    Finland  2.74926e+07
355  2013     9            4    Finland  3.39012e+07
356  2013    10            4    Finland   3.0053e+07
357  2013    11            4    Finland  3.73282e+07
358  2013    12            4    Finland  2.58992e+07
359  2014     1            4    Finland  2.84684e+07
360  2014     2            4    Finland  1.82185e+07
361  2014     3            4    Finland  3.98389e+07
362  2014     4            4    Finland  3.31585e+07
363  2014     5            4    Finland  2.38013e+07
364  2014     6            4    Finland  2.78953e+07
365  2014     7            4    Finland  3.01431e+07
366  2014     8            4    Finland  2.66335e+07
367  2014     9            4    Finland    3.802e+07
368  2014    10            4    Finland  2.36725e+07
369  2014    11            4    Finland  2.52172e+07
370  2014    12            4    Finland  3.01691e+07
371  2015     1            4    Finland  3.07064e+07
372  2015     2            4    Finland  5.01139e+07
373  2015     3            4    Finland  9.04492e+06
374  2015     4            4    Finland  3.10672e+07
375  2015     5            4    Finland  2.44465e+07
376  2015     6            4    Finland  3.19318e+07
377  2015     7            4    Finland  2.82871e+07
378  2015     8            4    Finland  2.87651e+07
379  2015     9            4    Finland  2.88178e+07
380  2015    10            4    Finland  3.12688e+07

[381 rows x 5 columns]

In [43]:
import pandas as pd


In [44]:
ds = pd.read_csv('promotional_expense.csv')
ds.head()

Year  Month    Country  Product_Type  Expense_Price
0  2013      1  Argentina             1      14749.307
1  2013      1  Argentina             2       1329.374
2  2013      1    Belgium             2        249.590
3  2013      1   Columbia             1       1893.122
4  2013      1   Columbia             2       1436.726

In [61]:
b = ds.loc[(ds['Country']=='Argentina')&(ds['Product_Type']==1)&(ds['Year']<2016)]
# # c = ds.loc[(ds['Country']=='Argentina')&(ds['Product_Type']==2)&(ds['Year']<2016)]
# d = ds.loc[(ds['Country']=='Argentina')&(ds['Product_Type']==2)]
# d
b
# ans = b['Expense_Price'].values.reshape((-1,1))
# ans

Year  Month    Country  Product_Type  Expense_Price
0    2013      1  Argentina             1      14749.307
6    2013      2  Argentina             1      12187.566
12   2013      3  Argentina             1      13076.579
18   2013      4  Argentina             1      14377.199
24   2013      5  Argentina             1      15652.861
30   2013      6  Argentina             1      11718.545
36   2013      7  Argentina             1      14144.888
42   2013      8  Argentina             1      12839.791
48   2013      9  Argentina             1      10788.309
54   2013     10  Argentina             1      16108.134
60   2013     11  Argentina             1      16242.067
66   2013     12  Argentina             1      11144.301
72   2014      1  Argentina             1      15316.880
78   2014      2  Argentina             1      14746.595
84   2014      3  Argentina             1      12998.792
90   2014      4  Argentina             1      15235.335
96   2014      5  Argentina             1      14499.779
102  2014      6  Argentina             1      13593.151
108  2014      7  Argentina             1      15204.593
114  2014      8  Argentina             1      13292.384
120  2014      9  Argentina             1      15306.694
126  2014     10  Argentina             1      14815.265
132  2014     11  Argentina             1      14102.804
138  2014     12  Argentina             1      16190.614
144  2015      1  Argentina             1      16242.659
150  2015      2  Argentina             1      12136.229
156  2015      3  Argentina             1      16330.077
162  2015      4  Argentina             1      14901.627
168  2015      5  Argentina             1      15056.339
174  2015      6  Argentina             1      19631.652
180  2015      7  Argentina             1      13289.789
186  2015      8  Argentina             1      14762.316
192  2015      9  Argentina             1      14722.833
198  2015     10  Argentina             1      13491.587
204  2015     11  Argentina             1      14529.224
210  2015     12  Argentina             1      13106.782

In [66]:
mylist_df.loc[(mylist_df['Year']==2015)&(mylist_df['Month']==6)&(mylist_df['Country']=='Argentina')&(mylist_df['Product_Type']==1)]['Sales'].values

array([41756400.0], dtype=object)

In [8]:
ds.shape

(435, 5)

In [75]:
for index,row in ds.iterrows():
    year = row['Year']
    month = row['Month']
    c = row['Country']
    p_ty = row['Product_Type']
    expense = row['Expense_Price']
    try:
        mylist_df.loc[(mylist_df['Year']==year)&(mylist_df['Month']==month)&(mylist_df['Country']==c)&(mylist_df['Product_Type']==p_ty),'Sales']-=expense
    except AttributeError:
        pass
mylist_df

Year Month Product_Type    Country        Sales
0    2013     1            1  Argentina  3.43313e+07
1    2013     2            1  Argentina  3.19934e+07
2    2013     3            1  Argentina   3.2517e+07
3    2013     4            1  Argentina  3.55743e+07
4    2013     5            1  Argentina  3.87734e+07
5    2013     6            1  Argentina  3.61849e+07
6    2013     7            1  Argentina  3.71196e+07
7    2013     8            1  Argentina  3.52987e+07
8    2013     9            1  Argentina  3.84271e+07
9    2013    10            1  Argentina  4.43816e+07
10   2013    11            1  Argentina  4.55091e+07
11   2013    12            1  Argentina  3.35994e+07
12   2014     1            1  Argentina  4.45855e+07
13   2014     2            1  Argentina  4.15479e+07
14   2014     3            1  Argentina  3.69444e+07
15   2014     4            1  Argentina  4.34327e+07
16   2014     5            1  Argentina  4.08489e+07
17   2014     6            1  Argentina  4.03631e+07
18   2014     7            1  Argentina  4.34438e+07
19   2014     8            1  Argentina  4.12895e+07
20   2014     9            1  Argentina  4.37681e+07
21   2014    10            1  Argentina  4.37623e+07
22   2014    11            1  Argentina  4.23613e+07
23   2014    12            1  Argentina  4.42271e+07
24   2015     1            1  Argentina  4.65644e+07
25   2015     2            1  Argentina  3.30566e+07
26   2015     3            1  Argentina  3.78482e+07
27   2015     4            1  Argentina  3.51218e+07
28   2015     5            1  Argentina    3.555e+07
29   2015     6            1  Argentina  4.17368e+07
..    ...   ...          ...        ...          ...
351  2013     5            4    Finland  3.29408e+07
352  2013     6            4    Finland   1.9155e+07
353  2013     7            4    Finland  2.71788e+07
354  2013     8            4    Finland  2.74913e+07
355  2013     9            4    Finland  3.38997e+07
356  2013    10            4    Finland  3.00516e+07
357  2013    11            4    Finland  3.73265e+07
358  2013    12            4    Finland   2.5898e+07
359  2014     1            4    Finland  2.84671e+07
360  2014     2            4    Finland  1.82176e+07
361  2014     3            4    Finland  3.98373e+07
362  2014     4            4    Finland   3.3157e+07
363  2014     5            4    Finland  2.38002e+07
364  2014     6            4    Finland  2.78939e+07
365  2014     7            4    Finland  3.01418e+07
366  2014     8            4    Finland  2.66323e+07
367  2014     9            4    Finland  3.80183e+07
368  2014    10            4    Finland  2.36714e+07
369  2014    11            4    Finland   2.5216e+07
370  2014    12            4    Finland  3.01677e+07
371  2015     1            4    Finland   3.0705e+07
372  2015     2            4    Finland  5.01127e+07
373  2015     3            4    Finland  9.04333e+06
374  2015     4            4    Finland  3.10658e+07
375  2015     5            4    Finland  2.44453e+07
376  2015     6            4    Finland  3.19303e+07
377  2015     7            4    Finland  2.82858e+07
378  2015     8            4    Finland  2.87638e+07
379  2015     9            4    Finland  2.88164e+07
380  2015    10            4    Finland  3.12674e+07

[381 rows x 5 columns]

In [77]:
mylist_df.to_csv('final_train_data.csv')